<?php

/**
 * BasePost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $image
 * @property string $title
 * @property Doctrine_Collection $Votes
 * 
 * @method integer             getId()    Returns the current record's "id" value
 * @method string              getImage() Returns the current record's "image" value
 * @method string              getTitle() Returns the current record's "title" value
 * @method Doctrine_Collection getVotes() Returns the current record's "Votes" collection
 * @method Post                setId()    Sets the current record's "id" value
 * @method Post                setImage() Sets the current record's "image" value
 * @method Post                setTitle() Sets the current record's "title" value
 * @method Post                setVotes() Sets the current record's "Votes" collection
 * 
 * @package    brat_or_not
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePost extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('post');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Vote as Votes', array(
             'local' => 'id',
             'foreign' => 'post_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}