<?php

/**
 * Post
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    brat_or_not
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Post extends BasePost
{
    public function getImagePath()
    {
        return "/uploads/images/{$this->image}";
    }

    /**
     * Get Total Votes for a Post
     *
     * @return int
     * @author Ryan McGrew <ryan.mcgrew@nerdery.com>
     **/
    public function getTotalVotes()
    {
        return $this->Votes->count();
    }

    /**
     * Get Total Number of Yes Votes
     *
     * @return int
     * @author Ryan McGrew <ryan.mcgrew@nerdery.com>
     **/
    public function getTotalYesVotes()
    {
        return $this->Votes
                    ->getTable()
                    ->findByIsBrat(true)
                    ->count();
    }

    /**
     * Return the percentage of Yes Votes
     *
     * @return string
     * @author Ryan McGrew <ryan.mcgrew@nerdery.com>
     **/
    public function getBratiness()
    {
        $percent = $this->getTotalYesVotes() / $this->getTotalVotes();
        $percent = floor($percent * 100);
        return "$percent%";
    }
}
