generator:
  class: sfDoctrineGenerator
  param:
    model_class:           post
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          post
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        image: { label: "Post Image" }
        title: { label: "Post Title" }
      list:
        display: [_image, =title, bratiness, totalYesVotes, totalVotes]
      filter:  
        display: [title]
      form:    ~
      edit:    ~
      new:     ~
